FT20-388 BE - Create and endpoint for POST client address
hamalsolutions/flashtrack-api pull request #11
Opened 2022-03-29 19:35 UTC by joselsanabria

2022-03-29 23:53 UTC, maacaro requested changes
@joselsanabria  muy bien los test por alli deje un par de comments de estylo en el codigo

2022-03-29 23:53 UTC, maacaro commented on src/server.js
> +  if (!firstName || !lastName || !emailAddress || !country || !streetAddress || !city || !state || !zipCode) return res.sendStatus(400);
@joselsanabria los bloques if siempre con llaves 
```
if(x>0){
 lo que sea
}
```

2022-03-29 23:53 UTC, maacaro commented on src/server.js
> +  res.json({
@esto no lleva un return?

2022-03-30 12:14 UTC, joselsanabria commented on src/server.js
> +  if (!firstName || !lastName || !emailAddress || !country || !streetAddress || !city || !state || !zipCode) return res.sendStatus(400);
if (!firstName || !lastName || !emailAddress || !country || !streetAddress || !city || !state || !zipCode) return res.sendStatus(400);{
    res.json({
      clientId: 1,
      firstName,
      lastName,
      emailAddress,
      country,
      streetAddress,
      city,
      state,
      zipCode,
    });
  }

2022-03-30 12:14 UTC, joselsanabria commented on src/server.js
> +  res.json({
if (!firstName || !lastName || !emailAddress || !country || !streetAddress || !city || !state || !zipCode) return res.sendStatus(400);{
    res.json({
      clientId: 1,
      firstName,
      lastName,
      emailAddress,
      country,
      streetAddress,
      city,
      state,
      zipCode,
    });
  }

2022-03-30 14:55 UTC, maacaro approved these changes
LGTM

2022-03-30 14:56 UTC, merged