endpoint client address
hamalsolutions/flashtrack-api pull request #4
Opened 2022-03-28 13:06 UTC by breylore

2022-03-28 17:49 UTC, maacaro requested changes

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +  /client/:clientId/address:
@breylore debe ser `/clients/...` en plural

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - in: "body"
@breylore hay u nparametro en el path el :clientId

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        200:
@breylore los HTTP metodos PUT y POST deben regrasar un status code de 201 cuando todo sale bien

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
@breylore no creo que vayamos a devolver xml

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +          description: "Products not found"
@breylore la descripcion seria como que Client Not Found

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
@breylore no creo que recibamos xml

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
no creo que devolvamos xml

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - in: "body"
@breylore al igual que el post aca hay un parametro en el path el clientId

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        200:
@breylore  esto deberia ser 201

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        200:
@breylore creo devuelve diferente creo es 201 tambien por fabor verificar de debe devolver el delete

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
@breylore no vamos a producir xml

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +        - name: "api_key"
@breylore aca el unico parametro es el del path /:clientId/

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +    put:
@breylore este put deberia estar en una de las siguientes rutas:
`/address/{:addressId}/` o `/clients/{clientsId}/address/{addressId}/`

2022-03-28 17:49 UTC, maacaro commented on swagger.yaml
> +    delete:
@breylore este **delete** deberia estar en una de las siguientes rutas:
`/address/{:addressId}/` o `/clients/{:clientsId}/address/{:addressId}/`

2022-03-28 20:27 UTC, breylore commented on swagger.yaml
> +  /client/:clientId/address:
Arreglado Clients

2022-03-28 20:31 UTC, breylore commented on swagger.yaml
> +        - in: "body"
Resuelto

2022-03-28 20:34 UTC, breylore commented on swagger.yaml
> +        - "application/xml"
Resuelto

2022-03-28 20:38 UTC, breylore commented on swagger.yaml
> +          description: "Products not found"
Listo (ops sorry! copy and paste)

2022-03-28 20:38 UTC, breylore commented on swagger.yaml
> +        - "application/xml"
ok

2022-03-28 20:38 UTC, breylore commented on swagger.yaml
> +        - "application/xml"
ok

2022-03-28 20:40 UTC, breylore commented on swagger.yaml
> +        - in: "body"
Listo

2022-03-28 20:48 UTC, breylore commented on swagger.yaml
> +        - name: "api_key"
si es el clientId? o el addressId? pq pide es el codigo del la direccion que voy a eliminar si?

2022-03-29 23:28 UTC, maacaro approved these changes
LGTM

2022-03-29 23:28 UTC, merged