FT20-406 Define Client endpoint
hamalsolutions/flashtrack-api pull request #5
Opened 2022-03-28 15:11 UTC by Yalwin

[FT20-406](https://hamal-solutions.atlassian.net/browse/FT20-406)

2022-03-28 17:28 UTC, maacaro requested changes

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +  /client:
@Yalwin esto debe ser /clients en plural

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
@Yalwin  no creo que devuelva xml solo vamos a devolver JSON

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +        "200":
@Yalwin  cuando el metodo es post o put el status code debe ser 201

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +          description: "Client not found"
@Yalwin hay ue tomar en cuenta que puede devolver 500

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +        "400":
@Yalwin falta la repuesta con estatus code 201 que ocurre cuando se ha podido hacer el update satisfactoriamente

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +        "400":
@Yalwin falta el status code con la respuesta exitosa

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
@Yalwin  no vamos a devolver xml

2022-03-28 17:28 UTC, maacaro commented on swagger.yaml
> +        - "application/xml"
@Yalwin creo que nosotros no vamos a devolver XML

2022-03-29 23:34 UTC, maacaro requested changes

2022-03-29 23:34 UTC, maacaro commented on swagger.yaml
> +  /Client/{idClient}:
@Yalwin la c debe ser minuscula y client en plural clients

2022-03-30 00:13 UTC, PedroLabrador commented on swagger.yaml
> +                type: array
@Yalwin al actualizar un cliente deberia retornar un objeto no un array (el cliente mismo actualizado)

2022-03-30 11:23 UTC, maacaro approved these changes
LGTM

2022-03-30 11:23 UTC, merged