FT20-409 Define client order generate EPC codes
hamalsolutions/flashtrack-api pull request #6
Opened 2022-03-28 16:39 UTC by PedroLabrador

## Overview

- POST endpoint for epc code generation given an idOrder for a client
- ignoring .prettierrc file

## Related Issues 

- [FT20-409](https://hamal-solutions.atlassian.net/browse/FT20-409)

2022-03-28 17:31 UTC, maacaro requested changes

2022-03-28 17:32 UTC, maacaro requested changes

2022-03-30 11:25 UTC, maacaro requested changes

2022-03-30 11:25 UTC, maacaro commented on swagger.yaml
> +  /orders/{idOrder}/generate-epc-codes:
@PedroLabrador deberia ser orderId? en lugar de idOrder ? no?

2022-03-30 13:06 UTC, PedroLabrador commented on swagger.yaml
> +  /orders/{idOrder}/generate-epc-codes:
pues si

2022-03-30 14:37 UTC, maacaro approved these changes
LGTM

2022-03-30 14:38 UTC, merged