FT20-385 Create Endpoint for GET countries
hamalsolutions/flashtrack-api pull request #9
Opened 2022-03-29 12:58 UTC by BigTorino

- [FT20-385](https://hamal-solutions.atlassian.net/browse/FT20-385)

2022-03-29 23:44 UTC, maacaro requested changes

2022-03-29 23:44 UTC, maacaro commented on src/server.js
> +app.get("/client/:idClient/countries", (req, res) => {
@BigTorino deberia ser `clientId`porque el client seria el adjetivo en te caso y el Id el sustantivo no?

2022-03-29 23:44 UTC, maacaro commented on src/server.js
> +app.get("/client/:idClient/countries", (req, res) => {
@BigTorino ojo en la definicion es `/countries` NO `/client/:idClient/conutries`

2022-03-29 23:44 UTC, maacaro commented on src/server.js
> +app.get("/client/:idClient/countries", (req, res) => {
@BigTorino hay un PR previo a este que contiene la definicion https://github.com/hamalsolutions/flashtrack-api/pull/8/files
y los objetos del array de countries contienen **id** y **name**

2022-03-30 00:26 UTC, PedroLabrador approved these changes

2022-03-30 11:25 UTC, maacaro approved these changes
LGTM

2022-03-30 11:26 UTC, merged